### PR TITLE
TFLite Support for RVC2

### PR DESCRIPTION
**Pull request by kozlov721**
Added support for conversion from `tflite` files for RVC2 platform.

### CODE REVIEW

**Review by klemen1999 — APPROVED** [review]
Are models exported with OpenVino>=2024.2.0 runnable on DepthAI since there the default version is lower (2022.1 based on [online blobconverter](https://blobconverter.luxonis.com/))

Otherwise LGTM

**Comment by kozlov721** [comment]
>Are models exported with OpenVino>=2024.2.0 runnable on DepthAI

I tested the exported models with `modelconverter benchmark` and they do run fine, so I hope it won't cause any issues. I'll tag the latest RVC2 image before this change so we can quickly test with older version in case there will be an issue with RVC2 models not running on DepthAI.

**Comment by tersekmatija** [comment]
> Are models exported with OpenVino>=2024.2.0 runnable on DepthAI

IMO this is highly dangerous. We'd rather test this on the whole ZOO as the MYRIAD was deprecated after 2022.3

**Comment by tersekmatija** [comment]
Possibly the right path instead would be TFLITE -> ONNX -> IR?

I am mainly worried about "compile_tool" failing if IR includes any new opsets for specific operations. I'd imagine at least some were introduced and some updated? These are the models we should be testing.

**Comment by kozlov721** [comment]
Another option might be to use the old versions when converting from ONNX and only switch to newer version of `mo` when converting from TFLITE. And print some warnings that this is not guaranteed to work.  Additionally, we might add a switch that would keep the old version even for TFLITE and try TFLITE -> ONNX conversion first.

**Pull request closed without merging**
